# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G


minecraft_version=1.21
yarn_mappings=1.21+build.1
loader_version=0.15.11

# Fabric API
fabric_version=0.100.1+1.21


mod_version=1.6.2
maven_group=net.digitalpear
modid=newworld


terraform_version=11.0.0-alpha.1
biolith_version=3.0.0
FD_version=1.21.1-2.2.7

#Runtime mods
emi=1.1.6+1.20.6+fabric